name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 */8 * * *" # Runs every 8 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download TryHackMe badge
        run: |
          mkdir -p assets
          curl -o assets/tryhackme-badge.png https://tryhackme-badges.s3.amazonaws.com/merehansheikh.png

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/tryhackme-badge.png
          git commit -m "Update TryHackMe badge" || echo "No changes to commit"
          git push
